ED-25519 Derived Extended Private Keys
Topl/Bifrost pull request #1428
Opened 2021-07-06 15:28 UTC by b-vennes

## Purpose

Most blockchains have a method for creating hundreds of thousands of signing key pairs and addresses from a root seed value (usually generated by a BIP-39 mnemonic or similar). Bifrost/Brambl needs a standard derived key implementation that lets users input some entropy (a mnemonic phrase) and get back a deterministic set of keys and addresses. 

## Approach

- Implements SLIP-23/BIP32-ED25519 protocols for deriving private ED-25519 signing keys from a root seed
- implements signing and serialization functions for `ExtendedPrivateKeyEd25519` keys so that they can be used as valid `Secrets` in the future

## Testing

- adds `ExtendedPrivateKeyEd25519Spec` with test vectors and generalized test scenarios for generating keys

## Tickets

- closes #1320

2021-07-29 05:21 UTC, scasplte2 requested changes
- Reproduce and document test vectors from rust-cardano or jormungandr
- reconsider public parent-> public child
- add more comments to SizedByteVector typeclass

2021-07-29 05:21 UTC, scasplte2 commented on common/src/main/scala/co/topl/attestation/keyManagement/derivedKeys/ExtendedPrivateKeyEd25519.scala
> +  def deriveChildKey(
just my two-cents but if I were looking at this 6 months later I might like to know that this function basically corresponds to section V.C

2021-07-29 05:21 UTC, scasplte2 commented on common/src/main/scala/co/topl/attestation/keyManagement/derivedKeys/package.scala
> +  def hmac512WithKey(key: ByteVector, data: ByteVector): ByteVector = {
could you clarify for me the interaction between this function and `object Pbkdf2Sha512`

2021-07-29 05:50 UTC, scasplte2 commented on common/src/main/scala/co/topl/attestation/keyManagement/derivedKeys/ExtendedPrivateKeyEd25519.scala
> +    val k = sha512.hash(iLeft.toArray).value
might note that this bit (particularly the bit flipping) is specified in V.A

2021-07-29 05:57 UTC, scasplte2 commented on common/src/main/scala/co/topl/attestation/keyManagement/derivedKeys/ExtendedPrivateKeyEd25519.scala
> +      SizedByteVector[ByteVector32].fit(iRight, ByteOrdering.LittleEndian),
I'm a little confused by this root chain code. It looks to me that in V.A the root chain code would be c <- H_{256}(0x01||kbar)

2021-08-05 08:06 UTC, scasplte2 commented on common/src/main/scala/co/topl/utils/SizedByteCollection.scala
> +trait SizedByteCollection[T] {
👍

2021-08-05 08:09 UTC, scasplte2 submitted a review, later dismissed
👍

2021-08-09 21:24 UTC, b-vennes commented on common/src/main/scala/co/topl/attestation/keyManagement/mnemonic/Mnemonic.scala
> +  ): Array[Byte] =
TODO: Update all the types in Mnemonic to use aliases

2021-08-09 21:48 UTC, b-vennes commented on common/src/main/scala/co/topl/attestation/keyManagement/mnemonic/mnemonic.scala
> +    String.format("%11s", BigInt(i).toString(2)).replace(' ', '0')
TODO: note why this is %11s

2021-08-09 21:51 UTC, b-vennes commented on common/src/main/scala/co/topl/utils/SizedByteCollection.scala
> +trait SizedByteCollection[T] {
TODO Consider naming:
- SizedBytes
- SizedByteVector
- something short

2021-08-13 18:12 UTC, scasplte2 commented on common/src/main/scala/co/topl/attestation/keyManagement/derivedKeys/ExtendedPrivateKeyEd25519.scala
> +  def derive(
@SeanCheatham this is a good example of what the key manager (keyRing, key chain, or whatever) will need to manage. Some entity will need to hold onto the top level key that is used to generate sub keys for the levels of the tree that we'll talk about in journal club today.

2021-08-23 03:15 UTC, scasplte2 commented
@b-vennes very nicely done! The change to Entropy and Phrase makes it much cleaner to me. I'm happy with this as is now so I am ready to merge.

2021-08-23 17:52 UTC, scasplte2 approved these changes
looked over the changes and nothing else to add 👍

2021-08-23 18:02 UTC, merged