MemPoolAuditor typed
Topl/Bifrost pull request #1634
Opened 2021-09-13 16:57 UTC by jingsting

## Purpose
- MemPoolAuditor and CleanupWorker need a refactor, there are some procedures that can simplified. 
- Transactions in the mem pool that become invalid due to changes to the state need to be eliminated sooner.

## Approach
- Merged CleanupWorker into MemPoolAuditor
- Turned MemPoolAuditor into a typed actor
- Added a check to eliminate transactions with invalid input box during mem pool cleanup

## Tests
- Tested if transactions that stayed in the mem pool longer than the mempoolTimeout will be eliminated
- Tested if transactions with invalid input box will be eliminated during cleanup

2021-09-13 21:04 UTC, jingsting commented on node/src/main/scala/co/topl/Heimdall.scala
> +      implicit val timeout: Timeout = Timeout(10.seconds)
remove this

2021-09-20 16:41 UTC, scasplte2 commented
is this ready to be converted @jingsting ?

2021-09-21 13:13 UTC, scasplte2 requested changes
Please address the comments below and make the todo about the messaging bit. Otherwise, this should be good to finish up shortly.

2021-09-21 13:13 UTC, scasplte2 commented on node/src/main/scala/co/topl/nodeView/MemPoolAuditor.scala
> +      context.pipeToSelf(withNodeView(splitIds(validatedTx, _))) {
@jingsting I don't think we need to change this now but in the future, when we see these sort of nested function calls, we should strive to make them a for comprehension (at least that is the first thing that comes to mind). Really, I want to avoid this nesting functions. To me that is a red flag that screams to be refactored because nested functions (1) make the code harder to read and reason about and (2) means that you have to have the error handling cases for the inner functions be captured by the outer functions. If you use something like a for-comprehension, or mapping, then the error handling can be embedded into the return type and handled by the calling function.

For this particular case, it doesn't seem much of an issue but I want you to double check that splitIds can't error out in some odd fashion. What are the failure conditions for all of the operations being performed in that function? Can any of them result in an exception? If so then we should change the output type to be an Either.

2021-09-21 13:13 UTC, scasplte2 commented on node/src/main/scala/co/topl/nodeView/MemPoolAuditor.scala
> +  private def active(validatedTx: TreeSet[Transaction.TX], iteration: Int): Behavior[ReceivableMessage] =
can we rename this to `awaitingDecision`? Since that is the state we are in.

2021-09-21 13:13 UTC, scasplte2 commented on node/src/main/scala/co/topl/nodeView/MemPoolAuditor.scala
> +        throw throwable
How does the typed actor system behave when you throw an error? Is this just logged to the console or does it crash the actor since no behavior is returned?

2021-09-21 13:13 UTC, scasplte2 commented on node/src/main/scala/co/topl/nodeView/MemPoolAuditor.scala
> +  private def rebroadcastTransactions(transactions: Seq[Transaction.TX]): Unit = {
I think we should update this pattern eventually. Maybe put a todo above this (we can get to it when we revamp the networking) but I'd like to just make this a tell to the nodeview synchronizer what modifiers to broadcast. That way the Mempool Auditor doesn't need to know anything about how to construct a message, since that really seems outside the scope of what the MempoolAuditor should do.

2021-09-24 22:36 UTC, scasplte2 reviewed
👍

2021-09-24 22:36 UTC, scasplte2 approved these changes
👍

2021-09-25 01:40 UTC, merged