Error response fixes and tests
Topl/Bifrost pull request #1643
Opened 2021-09-16 18:30 UTC by jingsting

## Purpose
- Make sure useful rpc error responses are returned for unlockKeyFile
- Check and test all the modifier query with invalid ids
- Remove local-testnet since we no longer use it

## Approach
- Added error response when there is no corresponding keyfile found for unlockKeyFile
- Added test for querying modifiers with an id containing non base58 characters
- Removed local-testnet

## Closes
- #1532 
- #1538 
- #1530

2021-09-20 16:16 UTC, scasplte2 requested changes
looks good, lets go over with everyone and look at the .toTry question. Otherwise this would be good to go I think.

2021-09-20 16:16 UTC, scasplte2 commented on common/src/main/scala/co/topl/attestation/keyManagement/KeyRing.scala
> +          } match {
I think you could do a `.toTry` here right?

2021-09-24 22:13 UTC, scasplte2 commented
These are all the changes that you wanted to incorporate right @jingsting ?

2021-09-24 22:18 UTC, jingsting commented
> These are all the changes that you wanted to incorporate right @jingsting ?

Yes, this has the changes that we wanted yesterday

2021-09-24 22:34 UTC, scasplte2 commented
👍 got it, going to merge

2021-09-24 22:35 UTC, scasplte2 approved these changes
🔥

2021-09-25 02:31 UTC, merged