Health check RPC
Topl/Bifrost pull request #1781
Opened 2021-11-29 22:42 UTC by jingsting

## Purpose
We need a way to check the status of the node, whether it's forging or not

## Approach
- Added an RPC method `topl_nodeStatus` that returns the forging status of the chain

## Tests
- Tested the responses when the forger is stopped and started

## Closes
#1423

2021-12-08 22:21 UTC, scasplte2 commented on topl-rpc/src/main/scala/co/topl/rpc/ToplRpc.scala
> +      case class Response(forgingStatus: String)
this isn't the node status, this is the forging status. If we want it to be the node status then I think we need to retrieve more data about the node

2021-12-08 22:22 UTC, scasplte2 commented on node/src/main/scala/co/topl/rpc/handlers/NodeViewRpcHandlerImpls.scala
> +  ): ToplRpc.NodeView.BlocksByIds.Response =
this should not be `ToplRpc.NodeView.BlockByIds.Reponse` it should be `ToplRpc.NodeView.BlocksInRange.Response`

2021-12-08 22:23 UTC, scasplte2 requested changes
please address the previous comments

2021-12-09 18:55 UTC, scasplte2 commented on topl-rpc/src/main/scala/co/topl/rpc/ToplRpc.scala
> +      case class Response(forgingStatus: String)
@jingsting I believe there is still work to be completed here? Once you have addressed it please ping me to let me know it is updated

2021-12-14 16:12 UTC, jingsting commented on node/src/main/scala/co/topl/rpc/handlers/NodeViewRpcHandlerImpls.scala
> +  ): ToplRpc.NodeView.BlocksByIds.Response =
Fixed, nice catch!

2021-12-14 18:13 UTC, scasplte2 approved these changes
👍

2021-12-14 19:30 UTC, merged