RPC for head info and segment of chain
Topl/Bifrost pull request #1782
Opened 2021-11-29 22:50 UTC by jingsting

## Purpose
- We need RRC methods for fetching the id and height of the best block without the other data about the block
- It way be convenient if we can retrieve a segment of the chain between a start height and an end height

## Approach
- Added a `topl_headInfo` RPC method
- Added a `topl_blocksInRange` RPC method

## Tests
- Added a test for `topl_headInfo` route
- Added a test for retrieving blocks with given start height and end height
- Added a test for the error response when start height and end height are incorrect (e.g. start height is greater than end height)

2021-12-08 21:50 UTC, scasplte2 commented on node/src/main/scala/co/topl/rpc/handlers/package.scala
> +        startHeight >= 1 && endHeight >= startHeight && bestBlockHeight >= startHeight,
what happens when bestBlockHeight < endHeight ? Shouldn't the last check be bestBlockHeight >= endHeight?

2021-12-08 21:55 UTC, scasplte2 commented on topl-rpc/src/main/scala/co/topl/rpc/ToplRpcErrors.scala
> +  val InvalidHeightRange: CustomError = CustomError(-32009, "Invalid height range")
didn't we also want to add a check that the user is not requesting too many blocks? Like the difference between end - start <=100. I also wonder if we should also add the `blockIdsInRange` so they can get back either a list of blocks of a list of ids

2021-12-08 21:58 UTC, scasplte2 requested changes
please address the
- logic for getting blocks compared to best block
- error when the user specifies an end height greater than the current height
- error when the user asks for too many blocks
- add a `blockIdsInRange` method

I would say limit the number of blocks from `blocksInRange` to be 100 (configurable via settings) and the number of block ids in the `blockIdsInRange` to be 1000 (also configurable)

2021-12-08 22:19 UTC, jingsting commented on topl-rpc/src/main/scala/co/topl/rpc/ToplRpcErrors.scala
> +  val InvalidHeightRange: CustomError = CustomError(-32009, "Invalid height range")
That was added in the methodAlias-rpc branch, sorry it got mixed into that one

2021-12-08 22:24 UTC, scasplte2 commented on topl-rpc/src/main/scala/co/topl/rpc/ToplRpcErrors.scala
> +  val InvalidHeightRange: CustomError = CustomError(-32009, "Invalid height range")
I just saw that. Thanks for letting me know 👍

2021-12-08 22:33 UTC, jingsting commented on node/src/main/scala/co/topl/rpc/handlers/package.scala
> +        startHeight >= 1 && endHeight >= startHeight && bestBlockHeight >= startHeight,
We will get back blocks from startHeight to bestBlockHeight if bestBlockHeight < endHeight. Do you think we need to enforce getting the exact range of blocks? I could add that condition here

2021-12-14 16:08 UTC, jingsting commented
> please address the
> 
> * logic for getting blocks compared to best block
> * error when the user specifies an end height greater than the current height
> * error when the user asks for too many blocks
> * add a `blockIdsInRange` method
> 
> I would say limit the number of blocks from `blocksInRange` to be 100 (configurable via settings) and the number of block ids in the `blockIdsInRange` to be 1000 (also configurable)

- added a check enforcing that bestBlockHeight >= endHeight
- the checks for block/tx number limit were added in a different branch
- `topl_blockIdsInRange` was added in `blockIdsInRange-rpc` branch

2021-12-14 19:30 UTC, scasplte2 approved these changes
🔥

2022-01-06 16:04 UTC, merged