Binary Codecs: Networking Layer
Topl/Bifrost pull request #1890
Opened 2022-01-26 23:36 UTC by b-vennes

## Purpose

- replace existing usage of `BifrostSerializer` instances in the `co.topl.network` package
- optimize networking layer to take advantage of the type-class pattern and refactors to the message structures

## Approach
- changes all possible message types into an enumeration of `MessageV1`
- implements a `Transmission` type which parses incoming and outgoing data into a strongly-typed value containing the message header (message code and message length) and the message content (a checksum and the data)
  - this type is clear to work with and can be converted to and from message types
- adds codecs for all message types and uses these codecs to convert message content from transmissions
- `Synchronizer` types define handlers for specific subtypes of message and provide
- `Synchronizer` types register a set of message codes defining the messages they would like to receive from the `NetworkController`

## Testing
- adds compatibility unit tests for the new network message codecs

## Tickets
- #1768

2022-01-28 03:47 UTC, scasplte2 approved these changes
👇 no other good place for that comment but overall this is really well done @b-vennes! It was a headache and a half when I first tried understanding how the messages interacted with one another and got into and out of the system. But this change feels like it draws the right lines in the right places by separating and disentangling complexities.

---
While reviewing, I was looking at `UByte` trying to see if it was used anywhere and noticed the type aliases in the valuetypes package object for `UByte, ULong, UShort, UInt`. Two questions came to mind. (1) Should `ULong` be a long? Shouldn't it need to go to a larger type similar to the others? (2) Since these are type aliases, are the type classes instances unique? Could we ever have a problem at runtime where `Codec[UByte]` is needed but `Codec[UShort]` is around so it gets used instead since `UByte` and `UShort` are both aliases for `Int`?

2022-01-28 03:47 UTC, scasplte2 commented on node/src/main/scala/co/topl/network/PeerConnectionHandler.scala
> +    networkControllerRef ! NetworkController.ReceivableMessages.TransmissionReceived(transmission, selfPeer)
I know this is a carry over but could we touch base on this `selfPeer`? I was initially having trouble recalling what the variable was for but now looking at it I think we may be able to get rid of it since I think it's only purpose is to be the internal reference (in the local ActorSystem) for communicating with a remote peer.

2022-01-28 03:47 UTC, scasplte2 commented on node/src/main/scala/co/topl/network/PeerConnectionHandler.scala
> +    networkControllerRef ! NetworkController.ReceivableMessages.TransmissionReceived(transmission, selfPeer)
we should probably address in a separate PR but leaving the comment here so we can chat

2022-01-28 03:47 UTC, scasplte2 commented on node/src/main/scala/co/topl/network/codecs/scodecs/network/peer/PeerCodecs.scala
> +  implicit val peerSpecCodec: Codec[PeerSpec] =
`PeerSpec` is such an awful name for what this is

2022-01-28 03:47 UTC, scasplte2 commented on node/src/main/scala/co/topl/network/message/Transmission.scala
> +case class Transmission(header: TransmissionHeader, content: Option[TransmissionContent]) {
This is a much easier thing to understand than how this was handled previously ✅

2022-01-28 03:47 UTC, scasplte2 commented on node/src/main/scala/co/topl/network/message/package.scala
> +  sealed trait Message {
ADTs for the win, this feels much more ergonomic and well defined now. Also thank you for including the descriptive comments

2022-01-28 03:47 UTC, scasplte2 commented on node/src/main/scala/co/topl/settings/AppContext.scala
> +import co.topl.network.peer
Looking around the codebase, it seems like we might be able to rename this to something along the lines of `RuntimeNetworkConfig` (just to be more descriptive) and we can remove the `features` val as it seems the only place it is used is in the `NetworkController` where we assume all nodes have the `LocalAddressFeature`. Even if we want to retain the ability to distinguish application version features, this is probably the wrong place to specify them.

2022-01-28 03:50 UTC, scasplte2 requested changes
apologies, meant to say lets chat about some of the comments before merging but overall I don't think there is much that needs to be changed

2022-01-28 15:22 UTC, b-vennes commented on node/src/main/scala/co/topl/network/PeerConnectionHandler.scala
> +    networkControllerRef ! NetworkController.ReceivableMessages.TransmissionReceived(transmission, selfPeer)
I think this might be a mistake. It should be sending the `TransmissionReceived` message with the connected peer who sent the transmission and not the self peer.

2022-01-28 15:31 UTC, b-vennes commented on node/src/main/scala/co/topl/network/PeerConnectionHandler.scala
> +    networkControllerRef ! NetworkController.ReceivableMessages.TransmissionReceived(transmission, selfPeer)
I think we might still need this concept so that we can send messages to the `PeerConnectionHandler` which in turns sends the transmissions to the connected peer.

2022-01-28 15:38 UTC, b-vennes commented
> While reviewing, I was looking at `UByte` trying to see if it was used anywhere and noticed the type aliases in the valuetypes package object for `UByte, ULong, UShort, UInt`. Two questions came to mind. (1) Should `ULong` be a long? Shouldn't it need to go to a larger type similar to the others? (2) Since these are type aliases, are the type classes instances unique? Could we ever have a problem at runtime where `Codec[UByte]` is needed but `Codec[UShort]` is around so it gets used instead since `UByte` and `UShort` are both aliases for `Int`?

An interesting thing about writing typeclasses in Scala and using type aliases is that the typeclass will only apply to the alias and not the aliased type. This means that if I want an implicit `Codec[ULong]`, then an implicit `Codec[Long]` will not work. It has to be the exact type. However, I can summon a `Codec[Long]` from implicit scope and call the `encode` function on a `ULong` value if I wish because the type alias system will automatically convert to the aliased type.

This is what has been biting us for things like the Proofs and Proposition codecs. The previous serialization scheme depended on inheritance of a BifrostSerializer in order to serialize the value which doesn't work for typeclasses.

2022-01-28 18:56 UTC, scasplte2 commented on node/src/main/scala/co/topl/network/PeerConnectionHandler.scala
> +    networkControllerRef ! NetworkController.ReceivableMessages.TransmissionReceived(transmission, selfPeer)
yes, we do need the concept, but the PeerConnectionHandler just sends an ActorRef to the NetworkController to effectively say "data to this IP needs to be forwarded to this ActorRef" but I don't think we need the selfPeer variable as when that "registration" happens couldn't we just query the underlying ActorRef for the PeerConnectionHandler actor?

2022-01-28 18:57 UTC, scasplte2 commented on node/src/main/scala/co/topl/network/codecs/scodecs/network/peer/PeerCodecs.scala
> +  implicit val peerSpecCodec: Codec[PeerSpec] =
we have a `PeerInfo` but `PeerMetadata` is at least a little more descriptive

2022-02-01 19:12 UTC, b-vennes commented on node/src/main/scala/co/topl/network/PeerConnectionHandler.scala
> +    networkControllerRef ! NetworkController.ReceivableMessages.TransmissionReceived(transmission, selfPeer)
I've created a new issue to remove usages of the `selfPeer` value. After looking some more it shouldn't be much work, but it will require some time for testing.

https://topl.atlassian.net/browse/CORE-1071

2022-02-03 01:24 UTC, scasplte2 approved these changes
🔥 ready when you are Branden

2022-02-04 02:11 UTC, merged