ConsensusVariable actor rework
Topl/Bifrost pull request #1906
Opened 2022-02-07 21:22 UTC by jingsting

## Purpose
Reworks for the consensus variable actor pull request

## Approach
- Refactored how the consensusVariable actor is initialized
- Added versions to keep in InMemoryKeyValueStore for testing rollbacks
- Added actor interface for the consensus variable actor

## Testing
- Bug fixes in tests
- Updated the tests to use InMemoryKeyValueStore instead of the LDBKeyValueStore

## Tickets
* #1837

2022-02-08 20:43 UTC, scasplte2 requested changes
this looks good @jingsting but lets chat about the approach on Thurs with everyone

2022-02-11 14:49 UTC, SeanCheatham commented on node/src/main/scala/co/topl/consensus/ConsensusVariables.scala
> +trait ConsensusVariablesInterface {
I suggest renaming this to something like `trait ConsensusVariablesHolder` with the implementation `class ActorConsensusVariablesHolder` to avoid including `Interface` in the class name.

2022-02-11 16:09 UTC, jingsting commented on node/src/main/scala/co/topl/consensus/ConsensusVariables.scala
> +        storage.latestVersionId() match {
Updated it to using `.exists` instead. Let me know if anyone has suggestions for improving this

2022-02-11 16:09 UTC, jingsting commented on node/src/main/scala/co/topl/consensus/ConsensusVariables.scala
> +  def getConsensusVariables: EitherT[Future, ConsensusVariablesInterface.GetConsensusParamsFailure, ConsensusParams]
Updated the names to `get`, `update`, and `rollback`

2022-02-11 16:11 UTC, jingsting commented on node/src/main/scala/co/topl/consensus/ConsensusVariables.scala
> +trait ConsensusVariablesInterface {
I updated the names to what Sean suggested 👍

2022-02-12 02:14 UTC, scasplte2 approved these changes
✔️

2022-02-12 02:14 UTC, merged