Dev Merge, Scodec Bits
Topl/Bifrost pull request #1946
Opened 2022-02-24 19:43 UTC by SeanCheatham

## Purpose
- The `tetra` branch is out-of-date with the `dev` branch
- The `tetra` branch uses the legacy encoding system for binary serialization and needs to be updated to the BV method

## Approach
- Merge `dev` branch
- Copy BV codec typeclasses from `common` into `byte-codecs`
- Create Identifiable, Signable, and Immutable typeclasses
- Create `tetra-byte-codecs` module with implementations of `byte-codecs` typeclasses
- Incorporate new typeclasses into Tetra codebase

## Testing
- TODO

## Tickets
_* closes #1921_

2022-02-28 16:33 UTC, b-vennes commented on json-codecs/src/main/scala/co/topl/codecs/json/tetra/ModelsJsonCodecs.scala
> +  implicit def propositionEncoder: Encoder[Proposition] = {
does circe offer any sort of support for Sum Types?

2022-02-28 17:39 UTC, SeanCheatham commented on json-codecs/src/main/scala/co/topl/codecs/json/tetra/ModelsJsonCodecs.scala
> +  implicit def propositionEncoder: Encoder[Proposition] = {
Circe has _some_ support for that sort of thing: https://circe.github.io/circe/codecs/adt.html#a-more-generic-solution

But when doing so manually, you can either do so without a "discriminator" (which would attempt to find the correct sum type using field names) or with a "discriminator" (which places a type byte at the front of the encoded data).

2022-02-28 17:40 UTC, SeanCheatham commented on byte-codecs/src/main/scala/co/topl/codecs/bytes/typeclasses/ImmutableCodec.scala
> +  @op("immutableBytes") def immutableBytes(value: T): ByteVector
I agree - I dislike `ImmutableBytes` for the same reason.  Perhaps `StableBytes` might work?

2022-02-28 17:43 UTC, SeanCheatham commented on brambl/src/main/scala/co/topl/credential/KeyCollection.scala
> +  def unlock[SK <: SecretKey: Persistable](evidence: TypedEvidence, password: Password): F[Option[SK]]
I think I prefer keeping `Persistable` as a context-bound to allow a user to override/specify the codec for their secret key.  This allows 3rd party developers to provide a specialized encoding scheme (that perhaps encrypts and decrypts the data bytes in addition to the encryption included internally).

2022-02-28 17:48 UTC, SeanCheatham commented on brambl/src/main/scala/co/topl/credential/CredentialIO.scala
> +      if (Files.exists(keyFilePath) && Files.isRegularFile(keyFilePath))
`Option.when` doesn't exist in Scala 2.12 :frowning:

I think if you're targeting an _application_ on Scala 2.13, then you're free to use Option.when.  But since `brambl` is a cross-versioned library, I figured it easier to just replace the usage of `Option.when`

2022-02-28 17:52 UTC, SeanCheatham commented on brambl/src/main/scala/co/topl/credential/Credential.scala
> +    case class HashLock(salt: Digest32, value: Byte) extends Credential {
This is one that @scasplte2 implemented so he may be able to provide more details.

This is essentially a "Proof of Knowledge of Text".  It creates a Box in the chain which is locked by a proposition containing some hash value.  To unlock the box, the person proves knowledge of the text/string that, when hashed, matches the hash on the proposition.  (The salt value further locks it down like when storing password hashes in a database)

2022-03-02 05:50 UTC, scasplte2 commented on brambl/src/main/scala/co/topl/credential/Credential.scala
> +    case class HashLock(salt: Digest32, value: Byte) extends Credential {
yes, Sean nailed the description. Hash Time Lock contracts are a useful primitve to have available (a HashLock && HeightLock) and can be used for atomic-swap contracts. 
https://academy.binance.com/en/glossary/hashed-timelock-contract

An atomic-swap is one where Alice has token A and wants token B, Bob has token B and wants A. So Alice will commit some amount of token A to a box that is locked with a HashLock. Bob can also create a box of token B using the same HashLock. Once, Bob's token B is locked then Alice can spend it since she knows the input value that produces the HashLock so she can create a valid proof. But in order to spend the funds that Bob locked up, Alice must reveal the secret value to claim the token B box. Finally, once the input is reveal, Bob can use it to claim the token A box. Addition of appropriate HieghtLocks then eliminate Alice's ability to claim both tokens and coupling with signing routines can allow for buybacks.

2022-03-02 06:24 UTC, scasplte2 commented on common/src/main/scala/co/topl/attestation/keyManagement/Keyfile.scala
> +object Keyfile {}
should remove this when we can get to it

2022-03-02 06:31 UTC, scasplte2 commented on common/src/main/scala/co/topl/codecs/binary/typeclasses/BinaryShow.scala
> +package co.topl.codecs.binary.typeclasses
Can we remove these typeclasses from `common` and have `common` depend on `byte-codecs`?

2022-03-02 06:54 UTC, scasplte2 commented on node/src/main/resources/application.conf
> +    version { value = 1.10.0 }
we don't need those values from above right? I think those are left over from Aaron trying to bring the Prosomo stakeholder over

2022-03-02 06:56 UTC, scasplte2 commented on node/src/main/scala/co/topl/consensus/genesis/HelGenesis.scala
> +      .decodeTransmitted[ModifierId]
probably makes more sense if this is `Immutable`

2022-03-02 13:52 UTC, SeanCheatham commented on common/src/main/scala/co/topl/codecs/binary/typeclasses/BinaryShow.scala
> +package co.topl.codecs.binary.typeclasses
Dion still uses `Array[Byte]` everywhere which is the default input/output of the codec typeclasses in `common`.  Once Dion is updated to use `ByteVector`, we should be able to get rid of the codec typeclasses from `common`.

2022-03-02 14:45 UTC, SeanCheatham commented on models/src/main/scala/co/topl/models/Box.scala
> +case class Box[V <: Box.Value](evidence: TypedEvidence, nonce: BoxNonce, value: V, data: Int)
Removed `Box#data`.  It seems to primarily be used for the `RequiredBoxState` proposition.  Should that be removed as well?

2022-03-02 14:45 UTC, SeanCheatham commented on node/src/main/resources/application.conf
> +    version { value = 1.10.0 }
Removed the Prosomo config values

2022-03-02 14:46 UTC, SeanCheatham commented on node/src/main/scala/co/topl/consensus/genesis/HelGenesis.scala
> +      .decodeTransmitted[ModifierId]
Once Dion is ready to switch over to the typeclasses in `byte-codecs`, we can change this to use `Immutable`

2022-03-05 05:48 UTC, scasplte2 commented on crypto/src/main/scala/co/topl/crypto/crypto.scala
> +  trait Implicits
@aaronschutza do you recall which branch you KES tests were on? I don't see them included here so just want to make sure we don't lose those updates and that they will (or are) included in Tetra

2022-03-05 05:54 UTC, scasplte2 commented on models/src/main/scala/co/topl/models/TaktikosAddress.scala
> +  paymentVKEvidence: Evidence, // todo: should be typed evidence, rename to spendingEvidence
nit picky, but I want to change these member names to be something like (spendingEvidence, stakingEvidence, bindingCommit) the last one may be generalizable to a Proof of Knowledge since you can construct a commitment scheme with such a primitive. It also feels like this may be pointing to something more abstract.

2022-03-05 05:59 UTC, scasplte2 commented on node/src/it/resources/postman-tests/docker-compose.yml
> +    command: -s test --apiKeyHash As3ZuwnL9LpoW3wz8HoDpHtZqJ4dhPFFnv87GYrnCYKj
we talked about changing this, lets slate it for 1.11

2022-03-05 12:21 UTC, scasplte2 requested changes
Waiting to go over notes with the team so we can record tickets into the ice box and what not. Then this will be ready to merge

2022-03-05 12:21 UTC, scasplte2 commented on typeclasses/src/main/scala/co/topl/typeclasses/ContainsEvidence.scala
> +      ratio => TypedEvidence(10: Byte, new Blake2b256().hash(ratio.immutableBytes))
Should we just incorporate the hash specification into the `ContainsEvidence` type class? Then we just have to pass in the type prefix and an instance of `ImmutableBytes` (since any evidence that we assign a type prefix must be remain immutably once it has been used on the network)

2022-03-05 12:21 UTC, scasplte2 commented on byte-codecs/src/main/scala/co/topl/codecs/bytes/typeclasses/ImmutableCodec.scala
> +  @op("immutableBytes") def immutableBytes(value: T): ByteVector
That is a good point that I had not thought about. `StableBytes` is pretty descriptive but what about `BackwardsCompatibleBytes`? It is long but I feel like it conveys the appropriate level of information needed

2022-03-05 12:21 UTC, scasplte2 commented on models/src/main/scala/co/topl/models/Box.scala
> +case class Box[V <: Box.Value](evidence: TypedEvidence, nonce: BoxNonce, value: V, data: Int)
It was really put there for `EnumeratedData` but needed to be used for the `RequiredBoxState` but no, the `RequiredBoxState` is a really really important piece of the extended-utxo contract system so I want to keep it around.

2022-03-07 15:55 UTC, b-vennes commented on byte-codecs/src/main/scala/co/topl/codecs/bytes/scodecs/ops/ScodecOps.scala
> +  def mapDecodeErr(fErr: Err => Err): Codec[T] =
`mapDecodeErr` is effectively a `leftMap` for a Scodec `Codec` instance. There is currently a way to `leftMap` on an `Attempt` once you've attempted a decode or encode, but there is no way to globally set what the error message should be. I've used this in a few places to provide better error messages than the default `expected X bits in the bit vector`.

2022-03-10 20:52 UTC, SeanCheatham commented on typeclasses/src/main/scala/co/topl/typeclasses/ContainsEvidence.scala
> +      ratio => TypedEvidence(10: Byte, new Blake2b256().hash(ratio.immutableBytes))
https://topl.atlassian.net/browse/CORE-1111

2022-03-10 20:52 UTC, SeanCheatham commented on node/src/main/scala/co/topl/nodeView/NodeView.scala
> +  // todo: this method causes delays in a block processing as it removes transactions from mempool and checks
Removed comment from code per discussion in review

2022-03-10 20:52 UTC, SeanCheatham commented on node/src/main/scala/co/topl/nodeView/MemPoolAuditor.scala
> +  // TODO: Jing - Consider changing this to just sending the ids to the networkController and let it form the message
Removed comment from code per discussion in review

2022-03-10 20:52 UTC, SeanCheatham commented on models/src/main/scala/co/topl/models/Box.scala
> +case class Box[V <: Box.Value](evidence: TypedEvidence, nonce: BoxNonce, value: V, data: Int)
Removed the commented code from ProofVerifier as discussed in review

2022-03-11 09:26 UTC, scasplte2 commented on crypto/src/main/scala/co/topl/crypto/crypto.scala
> +  trait Implicits
Aaron recalled the PR as https://github.com/Topl/Bifrost/pull/1846 and I verified that the tests are in the correct place

2022-03-11 09:27 UTC, merged