Add test vectors for Curve25519 key generation
Topl/Bifrost pull request #2016
Opened 2022-03-30 14:52 UTC by Tuxman

## Purpose
Generating Curve25519 public/private key pairs requires deterministic output from a given seed. The generation of this seed should be standardized across implementations using a set specification. We have chosen to use a modified version of [SLIP-0023](https://github.com/satoshilabs/slips/blob/master/slip-0023.md)  to derive the entropy of Curve25519 keys using the same key derivation scheme as ED25519 keys. The KDF and generation of Curve25519 keys is already in Bifrost, so this PR is adding unit tests to verify generating a seed from a given entropy. The test vectors used here will be placed in Topl's [Reference Crypto](https://github.com/Topl/reference_crypto) repo to define the specification for implementations in other languages and libraries, namely [BramblJS](https://github.com/Topl/BramblJS) and [BramblPy](https://github.com/Topl/BramblPy).

## Approach

## Testing
* 

## Tickets
* closes #1989

2022-04-19 15:16 UTC, b-vennes commented
Instead of moving `mnemonic` into the new `generation` package, would it be more clear to instead rename `mnemonic` to `generation`?

2022-04-19 15:20 UTC, b-vennes commented on crypto/src/test/resources/Curve25519AxolotlTestVectors.json
> +[  {
do we ever use these test vectors?

2022-05-24 13:54 UTC, b-vennes approved these changes
Looks good! But I had one suggestion with the `TestVector` abstract class.

2022-05-24 13:56 UTC, scasplte2 requested changes
I would like this to be better organized, there is no need for you to do anything @Tuxman. I just wanted to block this PR from being merged as I am not fully satisfied with where it is at but I will take care of getting it there.

2022-06-27 12:27 UTC, SeanCheatham commented on crypto/src/main/scala/co/topl/crypto/signing/ExtendedEd25519.scala
> +  lazy val instance: ExtendedEd25519 = {
If I remember correctly, `ExtendedEd25519` is not thread safe, so I don't think we want to include a shared companion object instance

2022-07-01 21:12 UTC, SeanCheatham commented on crypto/src/test/scala/co/topl/crypto/utils/Generators.scala
> +  def pickMnemonicSize(int: Int): MnemonicSize = int % 5 match {
This could probably be replaced by a `Gen[MnemonicSize]` if I understand its usage correctly.  i.e. 

```

val mnemonicSizeGen: Gen[MnemonicSize] =
  Gen.oneOf(MnemonicSizes.`12`, MnemonicSizes.`15`, MnemonicSizes.`18`, MnemonicSizes.`21`, MnemonicSizes.`24`)
  
  ```

2022-07-01 21:13 UTC, SeanCheatham approved these changes

2022-07-04 22:07 UTC, scasplte2 commented on crypto/src/test/scala/co/topl/crypto/utils/Generators.scala
> +  def pickMnemonicSize(int: Int): MnemonicSize = int % 5 match {
thanks for the suggestion @SeanCheatham

2022-07-04 22:08 UTC, scasplte2 approved these changes
🔍

2022-07-05 16:25 UTC, merged