Genus X-Api-Key Authentication
Topl/Bifrost pull request #2056
Opened 2022-04-21 15:38 UTC by b-vennes

## Purpose

Implementation of the X-Api-Key HTTP header protocol is necessary for basic security and restriction of Genus services running in production. The HTTP header `x-api-key` must be provided if required by the server and must hash to a value stored in the service.

## Approach

Implements `x-api-key` authentication using the `optionalHeaderValueByName` Akka directive, which secures access to a `Route` unless a specific header is provided. 

## Testing

- no new tests are added

## Tickets

- closes #1864

2022-04-30 03:24 UTC, scasplte2 requested changes

2022-04-30 03:24 UTC, scasplte2 commented on genus/src/main/resources/application.conf
> +      disableAuth = false
@b-vennes could you add some comments describing the settings in the `application.conf`. Some are obvious but in particular you should at least give the expected format for the `apiKeyHash` as the Base58 encoded hash output resulting from executing the Blake2b256 hash function on the the UTF-8 encoded API key (or something like that)

2022-05-03 21:25 UTC, SeanCheatham commented
Were you able to test this out manually in some way?  I'm curious how things look from the client-side of akka-grpc (or other gRPC frameworks) when attaching headers

2022-05-03 21:28 UTC, scasplte2 commented on genus/src/main/resources/application.conf
> +      disableAuth = false
@b-vennes any movement here?

2022-05-03 21:43 UTC, b-vennes commented on genus/src/main/resources/application.conf
> +      disableAuth = false
I've just added the comments

2022-05-03 21:45 UTC, b-vennes commented
> Were you able to test this out manually in some way? I'm curious how things look from the client-side of akka-grpc (or other gRPC frameworks) when attaching headers

I tested the headers using the `grpcurl` tool, but I've not yet tried using a generated client.

2022-05-05 18:13 UTC, b-vennes commented
> Were you able to test this out manually in some way? I'm curious how things look from the client-side of akka-grpc (or other gRPC frameworks) when attaching headers

I just tested and it is possible to set headers via the akka-grpc library. We will definitely want to provide some examples, and probably want to bake it into any official clients we create.

2022-05-06 13:54 UTC, b-vennes commented
@scasplte2 I have made the requested changes, so this should be ready for review again

2022-05-11 21:25 UTC, SeanCheatham approved these changes

2022-05-11 21:30 UTC, scasplte2 approved these changes

2022-05-11 21:32 UTC, scasplte2 requested changes
@b-vennes please ping the tech core channel once the conflicts are resolved but otherwise 👍

2022-05-13 19:23 UTC, scasplte2 approved these changes
👍

2022-05-16 19:38 UTC, merged