Draft: implemetation:BN-2547-TransactionWideSizeLimit (Do not merge)
Topl/Bifrost pull request #2591
Opened 2022-11-15 15:58 UTC by nandotorterolo

## Purpose
Draft Pr to understand if this is the right path to address this change
Enforce a transaction wide size limit (not just of the Transaction.Data).

## Approach

Sean's comment: While I like the idea of imposing a transaction-wide limit, I think there may be a couple considerations around how we achieve that. In particular, which mechanism do we use to turn the Transaction into 15kb? The Transmittable codec may result in varied length serialization once we move to protobuf. The Signable and Identifiable would be good candidates, but they omit the proofs from the bytes. So I think we would need a new one (probably just the "Immutable" one, from which Signable and Identifiable are derived).

Sized ImmutableCodec 

## Testing

Pair with @SeanCheatham to understand requirements, and implementation

## Tickets
BN-2547

2022-11-17 14:55 UTC, nandotorterolo commented on ledger/src/main/scala/co/topl/ledger/interpreters/TransactionSyntaxValidation.scala
> +      transactionStableCodec.immutableBytes(transaction).size <= Transaction.MaxDataLength,
change to:
> transaction.immutableBytes

2022-11-23 16:03 UTC, scasplte2 requested changes

2022-11-23 16:03 UTC, scasplte2 commented on ledger/src/main/scala/co/topl/ledger/interpreters/TransactionSyntaxValidation.scala
> +   * TODO Ask, if we should include proofs lengths
For now, lets keep a todo that we need to come back to this once the io transactions structure is set. I think the proofs are well enough defined as to not be obviously take advantage of them to embed lo0ts of data.

2022-11-23 16:03 UTC, scasplte2 commented on ledger/src/test/scala/co/topl/ledger/interpreters/TransactionSyntaxValidationSpec.scala
> -
happy to approve once this is added with immutable bytes

2022-11-23 16:05 UTC, nandotorterolo commented on ledger/src/main/scala/co/topl/ledger/interpreters/TransactionSyntaxValidation.scala
> +   * TODO Ask, if we should include proofs lengths
keep implementation, keep TODO note to re-think in the future if needed, implement test with this behavior, create Jira task (backlog )

2022-11-28 20:06 UTC, merged