[BN-018] Implement gRPC Health Check
Topl/Bifrost pull request #3040
Opened 2023-09-12 13:25 UTC by admiraladmirable

## Purpose

## Approach

## Testing

## Tickets
*

**Delete everything after and including this line after you are done reading and understand what to put for each section**

>### Purpose
>
>*State in plain words what the scope of the pull request and what problem it is trying to solve*
>
>### Approach
>
>*Enumerate the steps you took to create the code/changes contained in this pull request*
>
>### Testing
>
>*Specify all unit, integration, or end-to-end testing that is contained in this pull request*
>
>### Tickets
>
>*List tickets if any that are connected to this pull request in the following format:*
>
>_* closes #1234_

2023-09-14 22:02 UTC, admiraladmirable commented
I'll resolve the dependency conflicts tomorrow.

2023-09-15 15:00 UTC, nandotorterolo requested changes
Great PR, some comments, we can pair to resolve them

2023-09-15 15:00 UTC, nandotorterolo commented on node/src/main/scala/co/topl/healthcheck/HealthChecker.scala
> +              MonadThrow[F].raiseError(new StatusException(Status.NOT_FOUND))
question, I am confused about the response,  if we watch a service, and it is not in the map, you return ServingStatus.SERVICE_UNKNOWN, but if we check, and it is not there, it will return a Not found exception. Maybe I am reading wrong the code.

2023-09-18 14:29 UTC, admiraladmirable commented on node/src/main/scala/co/topl/healthcheck/HealthChecker.scala
> +              MonadThrow[F].raiseError(new StatusException(Status.NOT_FOUND))
That part was a bit confusing to me too. From following the [gRPC health check guide](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) they indicate that `SERVICE_UNKNOWN` is meant to be used just during streaming from the `watch` method. 

I'm not sure why they couldn't also use the `UNKOWN` status, but for now I'll just follow the recommendation (even if it is only elaborated on from a single comment 😵‍💫 )

2023-09-18 14:34 UTC, nandotorterolo commented on node/src/main/scala/co/topl/healthcheck/HealthChecker.scala
> +        implicit private val eqServingStatus: Eq[ServingStatus] =
I think you can remove this section, becuase is imported on import cats.implicits....

2023-09-18 14:34 UTC, nandotorterolo approved these changes

2023-09-18 20:22 UTC, admiraladmirable commented on topl-grpc/src/main/scala/co/topl/grpc/HealthCheckGrpc.scala
> +      List(
I decided to leave this a list for now since it makes merging lists cleaner down the line and the performance/memory impact will be minimal and only during initialization.

2023-09-18 21:14 UTC, merged